services:
  web:
    build: .
    image: ip-calc-web:1.0
    ports:
    - "8080:8080"
    environment:
      APP_VERSION: "1.0"
      DB_HOST: db
      POSTGRES_DB: ip-calc
      POSTGRES_USER: ip-calc
      POSTGRES_PASSWORD: ip-calc
    depends_on:
    - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ip-calc
      POSTGRES_USER: ip-calc
      POSTGRES_PASSWORD: ip-calc
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
